[package]
name = "convoy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.4"
logos = "0.13.0"
ureq = "2.7.1"
anyhow = "1.0.75"